server:
  port: 0

spring:
  application:
    name: payment

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  profiles:
    active: eclient

  config:
    import: configserver:http://localhost:8888
